### ISSUE TITLE
Bug: gerrit-based gsi submodule does not get pulled in during the submodule update command or with a 'git clone --recursive' command

### ISSUE THREAD

**Issue by slawrence87544** [frolovsa/UFS-RNR#29]
Problem: gsi submodule (gerrit-based) does not get downloaded after a 'git clone --recursive' or 'git submodule update --init --recursive' command.  The .ssh/config file has the correct host definition (see below) but the submodule update still fails.

Henry and I suspect that the issue is related to a firewall on the port described in the ssh host def.  A request to open up that port was submitted to the Microsoft team.

The curious thing is that the code can be cloned individually when directly hitting the repo with ' git clone https://github.com/NOAA-EMC/GSI ufsrnr-gsi' .

Host gerrit
HostName vlab.ncep.noaa.gov
    User steve.lawrence
    Port 29418

**Comment by HenryWinterbottom-NOAA** [comment]
@slawrence87544 I am able to clone the GSI using the recursive clone for the UFS-RNR repo. However, the issue is that pieces of the GSI that require Gerrit permissions -- namely, `libsrc` and `fix`. Further, cloning "individually" results in the same results (i.e., missing `fix` and `libsrc`).

If you are unable to pull any of the GSI from they NCEP repo, something might be missing from your configuration. Check that your `.ssh/config `is correct and that you have added the public RSA to [https://vlab.ncep.noaa.gov/code-review/settings/#SSHKeys].

**Comment by frolovsa** [comment]
I think we should push to be able to clone GSI on Azure.

But i wonder if we can still move forward with the "RnR-linght" prototype.
For example. focus on figuring out how to run a UFS ensemble forecast using
cylc. Play with native instal vs. running in a container.

**Comment by HenryWinterbottom-NOAA** [comment]
@frolovsa Yes, we can. The build system for UFS-RNR is intentionally designed such that the building of different applications (in this case, the GSI) can be turned off. Further, since we don't need a lot of the other bells and whistles, we can simply just build the UFS forecast component. This all assumes, however, that the UFS will play nicely with the stack that is built on Azure.

**Comment by slawrence87544** [comment]
I am seeing the same behavior that Henry is seeing (i.e. the recursive clone of the gerrit GSI repos libsrc and fix fail).  I will continue to build up the system to run the ufs forecast step as well as the cylc.

I will most likely run into conflicts with the current Azure stack, but I'll deal with those conflicts as they arise.  For now, I'll simply turn off the building of the gsi functionality.

**Comment by HenryWinterbottom-NOAA** [comment]
@slawrence87544 On RDHPCS Hera, I placed a file:

`/scratch2/BMC/gsienkf/Henry.Winterbottom/scratch/Steve.Lawrence/ufsrnr_build.RDHPCS-Hera.yaml`

This will build ONLY the UFS forecast model.

Please replace `sorc/tools/parm/ufsrnr_build.RDHPCS-Hera.yaml` with this file.

**Comment by slawrence87544** [comment]
After using this config file which removes other modules from the build proces (i.e. ufsrnr_gsi, ufsrnr_jedi, ufsrnr_ioda, ufsrnr_ufs_utils, and ufsrnr_stack), are you suggesting that the forcast can be run from cylc with just the build of the ufsrnr_forecast stack?

My question is. Are the ufsrnr_ufs_utils and ufsrnr_stack unnecessary builds in order to make the forecast run?

**Comment by HenryWinterbottom-NOAA** [comment]
@slawrence87544 That is correct. The Cylc suites do not yet implement the other components that are currently are built by the UFS-RNR.
